### ISSUE TITLE
Support for "setDefaultContentType" in oauth-promise

### ISSUE THREAD

**Issue by pdimeski96** [rudolfolah/node-oauth-libre#31]
I'm currently using oauth-promise and noticed that when delegating non-promise methods "setDefaultContentType" has been left out. Was this intentional? 

Added the following to support it: 

```
 /**
   * @instance
   * @method setDefaultContentType
   * @memberof OAuthPromise
   * @see OAuth#setDefaultContentType
   */
  "setDefaultContentType"
```

**Comment by rudolfolah** [comment]
good catch!
